### PR TITLE
Modifications to template

### PR DESCRIPTION
**Pull request by ashander**
for discussion/revision of info/curriculum/etc. see the FIXMEs, which need doing.

but also:
- [x] what room location?
- [x] who is the audience?
- [x] do we need two `R` sections?
- [x] sequencing of lessons correct?
- [x] times correct?

### CODE REVIEW

**Comment by moorepants** [comment]
Dan will have to provide the room and audience.

I think the sequencing is good. If you want to handle the two afternoon R sessions that would be good. I will probably leave at about 2 pm on Thursday to get back to my class in Davis. I can teach bash and git. We should do two R sections and I recommend we do the same one we taught in August, as it is more R than just programming. Times look correct.

**Comment by moorepants** [comment]
We should also get this on the SWC calendar. I told Dan we'd use eventbrite also to manage the signees. We could share the link with his office and give a sign up date and then he can advertise to other nearby agencies if we have more spaces. We can also enable a waitlist.

**Comment by moorepants** [comment]
Looks good to me.

**Comment by moorepants** [comment]
Does this need to be merged?

**Comment by ashander** [comment]
It's a PR from gh-pages to gh-old just to show what changes were made. The
changes are live though. I'll close the PR to avoid confusion

**Pull request closed without merging**
